---
# Defaults for deadline-client role
deadline_client_installer: "/tmp/deadline_client_installer"
deadline_client_version: "latest"

# Path to Deadline client installer on the target
deadline_installer_path: "/tmp/Thinkbox_Deadline_Client_Installer.run"
