---
---
- hosts: all
  become: true
  vars:
    resolve_installer: "/tmp/DaVinci_Resolve_Studio_20.2.1_Linux.run"
  roles:
    - role: davinci
      vars:
        davinci_installer: "{{ resolve_installer }}"
