---
# Handlers for nox_system role

- name: restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted

- name: reload systemd and restart firewalld
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
    
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
