---
# Defaults for domain_join role
domain_join_enabled: true
domain_name: "ad.noxvfx.com"
domain_controller: "dc-1.ad.noxvfx.com"
domain_admin_user: "noxadmin@AD.NOXVFX.COM"
# Provide this via ansible-vault or extra-vars when running the playbook
domain_admin_password: ""
domain_realm: "AD.NOXVFX.COM"

# NFS/autofs defaults
nfs_server: "192.168.11.9"
nfs_mounts_public: []
nfs_mounts_noxadmins: []

# Control whether to update all packages (set false for safe runs)
update_system: false
