---
- name: Install DasElement Lite on AlmaLinux 9.6
  hosts: all
  become: yes
  roles:
    - role: das-element
      daselement_variant: "lite"
      daselement_install_path: "/opt/{{ daselement_package_name }}-{{ daselement_lite_version }}"
