---
- name: Install Foundry Nuke 15.2v3
  hosts: all
  become: yes
  roles:
    - role: nuke
      nuke_version: "15.2"
      nuke_patch: "3"
      nuke_major_version: "15"
      nuke_executable_name: "Nuke15.2"
