---
# Installation settings
daselement_package_name: "das-element"
daselement_version: "latest"
daselement_lite_version: "latest"
daselement_install_path: "/opt/{{ daselement_package_name }}-{{ daselement_version }}"
daselement_expected_rpm: "/tmp/das_element_installer.rpm"

# Installer filename (place in Files/das-element/ or Files/)
daselement_installer_filename: "das-element-lite_2.1.4_lin.rpm"

# Variant: 'full' or 'lite'
daselement_variant: "full"

# Environment variables
daselement_license_server: "{{ das_element_license }}"
daselement_config_path: "/mnt/Library/_daselement/das-element.conf"
daselement_resources_path: "/mnt/Library/_daselement/resources"
