---
- name: Dump Storage Facts for Debugging
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather only storage facts
      ansible.builtin.setup:
        filter: ansible_devices

    - name: Display all storage facts for this host
      ansible.builtin.debug:
        var: ansible_devices
